import type { Metadata } from "next";
import '@mantine/core/styles.css';
import '@mantine/dropzone/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';
import { QuizProvider } from '@/context/QuizContext';


const theme = createTheme({
    fontFamily: 'Verdana, sans-serif',
    fontFamilyMonospace: 'Verdana, sans-serif',
    primaryColor: 'teal'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <QuizProvider>
            {children}
          </QuizProvider>
        </MantineProvider>
      </body>
    </html>
  );
}